name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      name:
        type: Publish
        description: Publish

  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build:components
      - run: pnpm test
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: cat .npmrc
      - run: npm login
      - run: npx release-it
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
